apiVersion: v1
kind: ConfigMap
metadata:
  name: sk044-config
  namespace: class-2
data:
  USER_NAME: "sk044"
  NAMESPACE: "class-2"
  BACKEND_URL: "http://sk044-backend-service:8000"
  OPENAI_MODEL: "gpt-4o-mini"
  CHROMA_PATH: "/app/chroma_db"
  DOCS_PATH: "/app/docs"